[workspace]
repository = "github.com/diodeinc/kicad"
pcb-version = "0.3"
members = []
vendor = ["github.com/diodeinc/registry/**"]

[assets]
"gitlab.com/kicad/libraries/kicad-footprints/Battery.pretty/BatteryHolder_Keystone_500.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Button_Switch_SMD.pretty/SW_SPST_B3U-1000P.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Button_Switch_THT.pretty/SW_PUSH_6mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Capacitor_SMD.pretty/CP_Elec_10x10.5.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Capacitor_SMD.pretty/CP_Elec_6.3x7.7.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Capacitor_SMD.pretty/CP_Elec_8x10.5.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-31_Kemet-D.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Connector_Coaxial.pretty/SMA_Samtec_SMA-J-P-H-ST-EM1_EdgeMount.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Connector_Coaxial.pretty/U.FL_Hirose_U.FL-R-SMT-1_Vertical.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Connector_USB.pretty/USB_C_Receptacle_HRO_TYPE-C-31-M-12.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Diode_SMD.pretty/D_0402_1005Metric.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Diode_SMD.pretty/D_SMA.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Diode_SMD.pretty/D_SOD-123.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Display.pretty/EA_DOGL128-6.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Display.pretty/EA_T123X-I2C.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Fuse.pretty/Fuse_1206_3216Metric.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Inductor_SMD.pretty/L_Bourns_SRR1260.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/LED_SMD.pretty/LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/OptoDevice.pretty/Maxim_OLGA-14_3.3x5.6mm_P0.8mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/OptoDevice.pretty/Renesas_DFN-6_1.5x1.6mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_BGA.pretty/Texas_DSBGA-6_0.95x1.488mm_Layout2x3_P0.4mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_BGA.pretty/Texas_PicoStar_BGA-4_0.758x0.758mm_Layout2x2_P0.4mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.55x2.48mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/DFN-16-1EP_3x5mm_P0.5mm_EP1.66x4.4mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/DFN-6-1EP_2x2mm_P0.65mm_EP1.01x1.7mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/DFN-6-1EP_3x3mm_P1mm_EP1.5x2.4mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/DFN-8-1EP_3x2mm_P0.5mm_EP1.36x1.46mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/DFN-8-1EP_3x2mm_P0.5mm_EP1.7x1.4mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/DHVQFN-16-1EP_2.5x3.5mm_P0.5mm_EP1x2mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/Nordic_AQFN-73-1EP_7x7mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/QFN-20-1EP_3x3mm_P0.4mm_EP1.65x1.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/QFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/QFN-28-1EP_4x5mm_P0.5mm_EP2.65x3.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/QFN-28-1EP_6x6mm_P0.65mm_EP4.25x4.25mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.6x3.6mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.7x3.7mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/QFN-48-1EP_7x7mm_P0.5mm_EP5.6x5.6mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/QFN-56-1EP_7x7mm_P0.4mm_EP3.2x3.2mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/QFN-56-1EP_7x7mm_P0.4mm_EP4x4mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/TDFN-14-1EP_3x3mm_P0.4mm_EP1.78x2.35mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/Texas_RGE0024C_VQFN-24-1EP_4x4mm_P0.5mm_EP2.1x2.1mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DFN_QFN.pretty/UQFN-20_3x3mm_P0.4mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_DIP.pretty/DIP-8_W7.62mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_LGA.pretty/Bosch_LGA-14_3x2.5mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_LGA.pretty/Bosch_LGA-8_2.5x2.5mm_P0.65mm_ClockwisePinNumbering.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_LGA.pretty/Bosch_LGA-8_3x3mm_P0.8mm_ClockwisePinNumbering.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_LGA.pretty/LGA-12_2x2mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_LGA.pretty/LGA-14_3x2.5mm_P0.5mm_LayoutBorder3x4y.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_LGA.pretty/LGA-14_3x5mm_P0.8mm_LayoutBorder1x6y.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_LGA.pretty/LGA-16_3x3mm_P0.5mm_LayoutBorder3x5y.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_LGA.pretty/LGA-28_5.2x3.8mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_QFP.pretty/LQFP-48_7x7mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_QFP.pretty/LQFP-64_10x10mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_QFP.pretty/TQFP-32_7x7mm_P0.8mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/MSOP-10_3x3mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/MSOP-8_3x3mm_P0.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/SOIC-20W_7.5x12.8mm_P1.27mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/SOIC-24W_7.5x15.4mm_P1.27mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.29x3mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/SOIC-8_3.9x4.9mm_P1.27mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/SOIC-8_5.3x5.3mm_P1.27mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/SSOP-24_5.3x8.2mm_P0.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/SSOP-28_5.3x10.2mm_P0.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/TSSOP-10_3x3mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/TSSOP-16_4.4x5mm_P0.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/TSSOP-20_4.4x6.5mm_P0.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/TSSOP-24_4.4x7.8mm_P0.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/TSSOP-28_4.4x9.7mm_P0.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/TSSOP-8_4.4x3mm_P0.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/VSSOP-10_3x3mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/VSSOP-8_2.3x2mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SO.pretty/VSSOP-8_3x3mm_P0.65mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SON.pretty/WSON-6-1EP_2x2mm_P0.65mm_EP1x1.6mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SON.pretty/WSON-8-1EP_2x2mm_P0.5mm_EP0.9x1.6mm_ThermalVias.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_SON.pretty/WSON-8-1EP_8x6mm_P1.27mm_EP3.4x4.3mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-223-3_TabPin2.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-23-5.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-23-6.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-23-8.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-23.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-323_SC-70.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-353_SC-70-5.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-363_SC-70-6.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-563.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-89-3.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/SOT-89-5.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/TO-252-3_TabPin2.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/TO-263-2.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/TO-263-5_TabPin3.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/TSOT-23-5.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_SMD.pretty/TSOT-23-6.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Package_TO_SOT_THT.pretty/TO-92_Inline.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Potentiometer_THT.pretty/Potentiometer_Bourns_3299W_Vertical.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/RF_Antenna.pretty/Johanson_2450AT18x100.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/RF_GPS.pretty/ublox_NEO.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/RF_GPS.pretty/ublox_SAM-M8Q.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/RF_Module.pretty/HOPERF_RFM69HW.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Sensor.pretty/Sensirion_SCD4x-1EP_10.1x10.1mm_P1.25mm_EP4.8x4.8mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Sensor_Distance.pretty/ST_VL53L1x.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Sensor_Humidity.pretty/Sensirion_DFN-4-1EP_2x2mm_P1mm_EP0.7x1.6mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Sensor_Humidity.pretty/Sensirion_DFN-4_1.5x1.5mm_P0.8mm_SHT4x_NoCentralPad.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Sensor_Humidity.pretty/Sensirion_DFN-8-1EP_2.5x2.5mm_P0.5mm_EP1.1x1.7mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Sensor_Motion.pretty/Analog_LGA-16_3.25x3mm_P0.5mm_LayoutBorder3x5y.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Sensor_Motion.pretty/InvenSense_QFN-24_3x3mm_P0.4mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-footprints/Sensor_Motion.pretty/InvenSense_QFN-24_4x4mm_P0.5mm.kicad_mod" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Amplifier_Current.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Analog.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Analog_ADC.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Analog_DAC.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Battery_Management.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Buffer.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Connector.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Device.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Diode.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Display_Character.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Display_Graphic.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Driver_LED.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Interface.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Interface_CAN_LIN.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Interface_Expansion.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Interface_UART.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Interface_USB.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/LED.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_Espressif.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_Microchip_ATmega.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_Microchip_ATtiny.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_Microchip_SAMD.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_Nordic.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_RaspberryPi.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_ST_STM32F0.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_ST_STM32F1.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_ST_STM32F4.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_ST_STM32G0.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/MCU_ST_STM32G4.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Memory_Flash.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Oscillator.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Power_Management.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Power_Protection.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/RF_Amplifier.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/RF_GPS.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/RF_Module.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Reference_Voltage.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Regulator_Linear.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Regulator_SwitchedCapacitor.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Regulator_Switching.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor_Distance.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor_Energy.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor_Gas.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor_Humidity.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor_Magnetic.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor_Motion.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor_Optical.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor_Temperature.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Sensor_Touch.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Switch.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/Timer_PLL.kicad_sym" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols/power.kicad_sym" = "9.0.3"
